"use client";

import * as React from "react";
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";

type TabKey = "summary" | "checklist" | "risks" | "draft";

const TABS: Array<{ key: TabKey; label: string }> = [
  { key: "summary", label: "Executive summary" },
  { key: "checklist", label: "Checklist" },
  { key: "risks", label: "Risks" },
  { key: "draft", label: "Draft outline" },
];

function usePrefersReducedMotion() {
  const [reduced, setReduced] = React.useState(false);

  React.useEffect(() => {
    const mql = window.matchMedia("(prefers-reduced-motion: reduce)");
    const onChange = () => setReduced(mql.matches);
    onChange();
    mql.addEventListener?.("change", onChange);
    return () => mql.removeEventListener?.("change", onChange);
  }, []);

  return reduced;
}

function MetaChip({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded-full border bg-background/60 px-2.5 py-1 text-[11px] text-muted-foreground">
      {children}
    </span>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return <div className="text-sm font-semibold">{children}</div>;
}

function BodyText({ children }: { children: React.ReactNode }) {
  return <div className="mt-2 text-sm text-muted-foreground leading-relaxed">{children}</div>;
}

function FadeContainer({
  activeKey,
  children,
}: {
  activeKey: string;
  children: React.ReactNode;
}) {
  return (
    <div key={activeKey} className="animate-in fade-in slide-in-from-right-2 duration-300">
      {children}
    </div>
  );
}

export function OutputPreview({ className }: { className?: string }) {
  const prefersReducedMotion = usePrefersReducedMotion();
  const [active, setActive] = React.useState<TabKey>("summary");
  const [isInteracting, setIsInteracting] = React.useState(false);

  React.useEffect(() => {
    if (prefersReducedMotion) return;
    if (isInteracting) return;

    const idx = TABS.findIndex((t) => t.key === active);
    const next = TABS[(idx + 1) % TABS.length]?.key ?? "summary";

    const id = window.setInterval(() => {
      setActive(next);
    }, 5200);

    return () => window.clearInterval(id);
  }, [active, prefersReducedMotion, isInteracting]);

  function onSelect(key: TabKey) {
    setActive(key);
  }

  return (
    <Card
      className={cn("rounded-2xl border bg-background/70 backdrop-blur", className)}
      onMouseEnter={() => setIsInteracting(true)}
      onMouseLeave={() => setIsInteracting(false)}
      onFocusCapture={() => setIsInteracting(true)}
      onBlurCapture={() => setIsInteracting(false)}
    >
      <CardContent className="p-5 md:p-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="h-2.5 w-2.5 rounded-full bg-red-500/70" />
            <span className="h-2.5 w-2.5 rounded-full bg-yellow-500/70" />
            <span className="h-2.5 w-2.5 rounded-full bg-green-500/70" />
          </div>
          <div className="text-xs text-muted-foreground">Preview</div>
        </div>

        <div className="mt-4">
          <div className="text-xs text-muted-foreground">
            Example output generated by AI models tailored for tender and RFP analysis.
          </div>
        </div>

        <div className="mt-4 flex flex-wrap gap-2" role="tablist" aria-label="Output preview tabs">
          {TABS.map((t) => {
            const selected = t.key === active;
            return (
              <button
                key={t.key}
                type="button"
                role="tab"
                aria-selected={selected}
                className={cn(
                  "rounded-full border px-3 py-1.5 text-xs transition",
                  selected
                    ? "bg-foreground text-background"
                    : "bg-background/60 text-muted-foreground hover:text-foreground"
                )}
                onClick={() => onSelect(t.key)}
              >
                {t.label}
              </button>
            );
          })}
        </div>

        <div className="mt-5 rounded-2xl border bg-background/60 p-4 md:p-5">
          {active === "summary" ? (
            <FadeContainer activeKey="summary">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <SectionTitle>Executive summary</SectionTitle>
                <div className="flex flex-wrap gap-2">
                  <MetaChip>Scope identified</MetaChip>
                  <MetaChip>14 requirements</MetaChip>
                  <MetaChip>2 key deadlines</MetaChip>
                </div>
              </div>

              <BodyText>
                <ul className="mt-2 space-y-2">
                  <li className="flex gap-3">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/60" />
                    <span>This tender covers supply and maintenance services for a three-year period.</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/60" />
                    <span>Mandatory technical requirements are clearly defined, with limited flexibility.</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/60" />
                    <span>Evaluation is based on price, delivery timeline, and compliance with standards.</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/60" />
                    <span>No alternative proposals are allowed.</span>
                  </li>
                  <li className="flex gap-3">
                    <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-foreground/60" />
                    <span>Submission deadline is fixed and extensions are not mentioned.</span>
                  </li>
                </ul>
              </BodyText>
            </FadeContainer>
          ) : null}

          {active === "checklist" ? (
            <FadeContainer activeKey="checklist">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <SectionTitle>Requirements checklist</SectionTitle>
                <div className="flex flex-wrap gap-2">
                  <MetaChip>AI extracted</MetaChip>
                  <MetaChip>Review required</MetaChip>
                </div>
              </div>

              <div className="mt-4 grid gap-2 text-sm text-muted-foreground">
                {[
                  { t: "ISO 9001 certification required", s: "Complete" },
                  { t: "Financial statements for last 2 years", s: "Needs review" },
                  { t: "Technical datasheets attached", s: "Complete" },
                  { t: "Delivery timeline specified", s: "Needs review" },
                  { t: "Acceptance criteria defined", s: "Complete" },
                  { t: "Penalty clauses included", s: "Missing" },
                ].map((row) => (
                  <div
                    key={row.t}
                    className="flex items-center justify-between gap-3 rounded-xl border bg-background/60 px-3 py-2"
                  >
                    <span className="leading-relaxed">{row.t}</span>
                    <span className="shrink-0 rounded-full border bg-background px-2.5 py-1 text-[11px] text-muted-foreground">
                      {row.s}
                    </span>
                  </div>
                ))}
              </div>
            </FadeContainer>
          ) : null}

          {active === "risks" ? (
            <FadeContainer activeKey="risks">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <SectionTitle>Risks and open points</SectionTitle>
                <div className="flex flex-wrap gap-2">
                  <MetaChip>Tender-specific AI</MetaChip>
                  <MetaChip>Review recommended</MetaChip>
                </div>
              </div>

              <div className="mt-4 grid gap-3 text-sm">
                <div className="rounded-xl border bg-background/60 p-3">
                  <div className="text-xs font-semibold">Proceed</div>
                  <div className="mt-1 text-sm text-muted-foreground leading-relaxed">
                    Requirements are standard and aligned with typical industry practices.
                  </div>
                </div>

                <div className="rounded-xl border bg-background/60 p-3">
                  <div className="text-xs font-semibold">Proceed with caution</div>
                  <div className="mt-1 text-sm text-muted-foreground leading-relaxed">
                    Delivery penalties are high and not clearly capped.
                  </div>
                </div>

                <div className="rounded-xl border bg-background/60 p-3">
                  <div className="text-xs font-semibold">Hold – potential blocker</div>
                  <div className="mt-1 text-sm text-muted-foreground leading-relaxed">
                    Liability terms are open-ended and may require legal clarification.
                  </div>
                </div>
              </div>
            </FadeContainer>
          ) : null}

          {active === "draft" ? (
            <FadeContainer activeKey="draft">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <SectionTitle>Draft proposal outline</SectionTitle>
                <div className="flex flex-wrap gap-2">
                  <MetaChip>AI generated</MetaChip>
                  <MetaChip>Editable</MetaChip>
                </div>
              </div>

              <div className="mt-4 text-sm text-muted-foreground leading-relaxed">
                <ol className="list-decimal space-y-1 pl-5">
                  <li>Introduction and company overview</li>
                  <li>Understanding of scope and objectives</li>
                  <li>Technical approach and compliance</li>
                  <li>Delivery plan and milestones</li>
                  <li>Risk management considerations</li>
                  <li>Commercial terms</li>
                  <li>Appendices and references</li>
                </ol>
              </div>
            </FadeContainer>
          ) : null}
        </div>

        <div className="mt-3 text-xs text-muted-foreground">
          Preview content is illustrative. Final results depend on the tender document.
        </div>
      </CardContent>
    </Card>
  );
}
